# PRODUCT_COPY_FILES += \
#     device/samsung/a9lte/recovery/root/etc/recovery.fstab:recovery/root/etc/recovery.fstab

# PRODUCT_USE_DYNAMIC_PARTITIONS := false

# code generated by AI
PRODUCT_COPY_FILES += \
    device/samsung/a9lte/init.rc:root/init.a9lte.rc
